# Generated by Django 4.0.4 on 2022-05-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
