# Generated by Django 4.0.4 on 2022-05-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malti', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='number',
            new_name='mobile',
        ),
    ]
