# Generated by Django 4.0.4 on 2022-05-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malti', '0003_rename_number_contactus_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='firstname',
        ),
    ]
